name: Frontend CI/CD

on:
  push:
    branches:
      - ci-cd
    paths:
      - 'frontend/**'
      - '.github/workflows/frontend-cicd.yml'
  workflow_dispatch:

jobs:
  docker:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Extract metadata
        run: |
          echo "SHORT_SHA=${GITHUB_SHA::7}" >> $GITHUB_ENV

      - name: Build and Push frontend image
        uses: docker/build-push-action@v6
        with:
          context: ./frontend
          file: ./frontend/Dockerfile
          push: true
          tags: |
            gpyo0111/mzc-frontend:${{ github.sha }}
            gpyo0111/mzc-frontend:ci-cd-${{ env.SHORT_SHA }}

  deploy:
    needs: docker
    runs-on: [self-hosted, Linux, X64, k8s-cp, deploy]

    steps:
      - name: Deploy frontend to Kubernetes
        run: |
          kubectl set image deployment/mzc-frontend frontend=gpyo0111/mzc-frontend:${{ github.sha }} -n mzc
          kubectl rollout status deployment/mzc-frontend -n mzc
          kubectl get deployment mzc-frontend -n mzc -o yaml | grep image:
          kubectl get pods -n mzc -o wide